[package]
name = "chip8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
env_logger = "0.10.0"
image = "0.24.6"
pollster = "0.3.0"
wgpu = "0.16.0"
winit = "0.28.5"